### PR TITLE
fix crash when using from cli

### PR DESCRIPTION
**Pull request by dgobaud**
require.main is undefined when running from cli - don't use unless it exists

### CODE REVIEW

**Comment by Kehrlann** [comment]
Hi @dgobaud, thanks for contributing 👋

Could you please add a bit of context to this PR ? Specifically, I'm looking for repro steps for the bug this PR will fix. I'm not sure I understand what the bug is.

Also, before accepting a PR we usually want a few test cases specifying the behavior.

Cheers !

**Comment by dgobaud** [comment]
yes try this 

```
node -i
> moduleAlias = require("module-alias");
{ [Function: init]
  addPath: [Function: addPath],
  addAlias: [Function: addAlias],
  addAliases: [Function: addAliases],
  isPathMatchesAlias: [Function: isPathMatchesAlias],
  reset: [Function: reset] }
> 
> 
> moduleAlias.addPath(path.resolve(""));
TypeError: Cannot read property 'paths' of undefined
    at Function.addPath (/.../node_modules/module-alias/index.js:85:38)
```

**Comment by Kehrlann** [comment]
I see. What would the use-case be for trying to run module-alias from the cli ?

**Comment by dgobaud** [comment]
I have a Firebase typescript project that uses it. Typescript compiles it to JS in lib folder. I have a utils folder. To make it work when running the compiled JS I do

```js
moduleAlias = require("module-alias");

// because of https://github.com/ilearnio/module-alias/pull/65
try { moduleAlias.addPath(path.resolve("")); } catch (e) {};

utils = require("./utils");
```

**Comment by Kehrlann** [comment]
Mmmh I tried a basic example myself and it worked. I'd like to better understand the problem before fixing it with those if-checks.

I probably missed a few details. Could you maybe share a sample codebase showcasing the problem ? In the form of a small github repo ? Anyway, thanks a lot for contributing and helping use improve module-alias :bowing_man:

**Comment by dgobaud** [comment]
it works BUT you can see the exception above itll crash your code if you dont catch it

**Comment by Kehrlann** [comment]
I can't reproduce it locally, see this repo: https://github.com/Kehrlann/module-alias-typescript . Feel free to send you own minimal repo so that I can take a look at it.

**Comment by dgobaud** [comment]
but you don't need type script just do the following

node -i
moduleAlias = require("module-alias");
moduleAlias.addPath(path.resolve(""));

and you get below error

TypeError: Cannot read property 'paths' of undefined
    at Function.addPath (/.../node_modules/module-alias/index.js:85:38)

**Comment by Kehrlann** [comment]
Ok I finally got some time to look into it. Summary of the findings:
1. As stated previously, when running from the node REPL (e.g. just running `node`), the following code throws an exception, because `require.main` is undefined:
```
const moduleAlias = require("module-alias");
moduleAlias.addPath(path.resolve(""));
```

2. However, the code has a side-effect: it adds the resolved path to module-alias' internal `modulePaths` array. If we guarded against `require.main` being undefined, we would be able to add to `modulePaths` without the exception. Having this allows to resolve some packages using `require.resolve`.

3. This has a single use case. Imagine you have a `utils` package at the root of your directory. You then run a REPL and execute:
```
require('./utils'); // <-this always works ✅
require.resolve('utils', { paths: [""] }); // <- this always succeeds ✅
require.resolve('utils', { paths: ["/some/path"] }); // <- this fails before using addPath ❓❌

const path = require('path');
const moduleAlias = require("module-alias");
moduleAlias.addPath(path.resolve("")); // whether this throws or not does no affect the rest of the script

require('utils'); // <- this fails  ❌
require.resolve('utils'); // <- still fails  ❌
require.resolve('utils', { }); // <- still fails  ❌
require.resolve('utils', { paths: ["/some/path"] }); // <- this now works  ❓✅
```

Then the question is: is it worth it to guard against `require.main` being undefined for a user:
- wanting to use `require.resolve('some-module', { paths: ["some/unrelated/path"] })` after `moduleAlias.addPaths("my/modules")` in the REPL
- when instead they could just use `require.resolve('some-module', { paths: ["some/unrelated/path", "my/modules"] })` without module-alias ?

I don't think it's worth it, unless there are other more compelling use-cases.

**Comment by dgobaud** [comment]
ok so i found the issue it is more complicated from the REPL I require a file if i don't have below 2 lines then if the file itself imports as require('utils') it fails. below is generated JS from my TS project that uses module-alias. when i import in REPL I must first have below or it fails

```
moduleAlias = require("module-alias");

// because of https://github.com/ilearnio/module-alias/pull/65
try { moduleAlias.addPath(path.resolve("")); } catch (e) {};
```

```js
"use strict";
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (Object.hasOwnProperty.call(mod, k)) result[k] = mod[k];
    result["default"] = mod;
    return result;
};
Object.defineProperty(exports, "__esModule", { value: true });
const js_lib_1 = require("@passfolio/js-lib");
const consts = __importStar(require("consts"));
exports.emailAddComplianceAddresses = (email) => {
    if (['production', 'beta'].includes(js_lib_1.kms.settings.CONFIG_ENV)) {
        email.to = 'alvaro.pereyra@panchainsecurities.com';
        email.cc = ['compliance@panchainsecurities.com', 'francesco@innreg.com'];
        email.bcc = consts.email.COMPLIANCE_EMAIL;
    }
};
//# sourceMappingURL=emailAddComplianceAddresses.js.map
```

**Comment by Kehrlann** [comment]
Ok I see. Sounds good to me ! Thanks for taking the time to explain.

Could you please add test cases so we can merge this ?

**Pull request closed without merging**
